// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xowjpavycntiajuwvkts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhvd2pwYXZ5Y250aWFqdXd2a3RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI3MzE4ODQsImV4cCI6MjA0ODMwNzg4NH0._lmnkLM_jjd_dlHJksRD7yvBQB1VGGESX4QxoNRxA1g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);